### ISSUE TITLE
needs cargo updated to parse latest ed2018 crates

### ISSUE THREAD

**Issue by matthiaskrgr** [kbknapp/cargo-outdated#141]
The latest cargo shipped by rust nightly has the ````edition = "2018"```` feature stabilized but cargo outdated still relies on cargo `0.28` which does not have the feature stabilized.

Thus cargo outdated fails to parse `Cargo.toml`'s which use the ed2018 feature without the feature gate.
````
 error: failed to parse manifest at `/home/matthias/vcs/github/cargo-cache/Cargo.toml`
Caused by:
  editions are unstable
Caused by:
  feature `edition` is required
consider adding `cargo-features = ["edition"]` to the manifest
````

**Comment by joelgallant** [comment]
This is due to the `Manifest` struct not holding on to `cargo-features`, so the TempProject does not write them to its `Cargo.toml` (causing the parsing of it later on to fail).

https://github.com/joelgallant/cargo-outdated/commit/6930e6a83039829cdacc5f4576426db71f3a5dc2

This patch gets some of the way there, but the TempProject thing requires more work. I might guess that the author will just wait for this to stabilize instead of adding work for themselves, but carrying over `cargo-features` seems worthwhile nonetheless.

**Comment by WyseNynja** [comment]
I just ran into this. Worked around it by commenting out `edition = "2018"` in my Cargo.toml when I need to run `cargo outdated`.

**Comment by svenstaro** [comment]
Isn't this going to fix itself once the next rust is released which will bring edition 2018 to stable?

**Comment by aldanor** [comment]
Nope; 2018 is out today, this still fails on 1.31 stable.

**Comment by joelgallant** [comment]
Is because it uses the API of an older version of cargo

**Comment by est31** [comment]
Particularly sad for me because I just updated my copy of cargo-outdated from an ancient version that didn't have the edition feature gating yet to the broken one... I guess I'll use @bbigras 's [workaround](https://github.com/kbknapp/cargo-outdated/pull/145#issuecomment-448351734) for the time being.

**Comment by kornelski** [comment]
This is fixed. It's waiting for crates.io release, but for now you can also install it from git.

**Comment by dbrgn** [comment]
Any chance for a crates.io release? :slightly_smiling_face:

**Comment by kornelski** [comment]
About the release, please see #153
