### ISSUE TITLE
rustc call fails with "unknown print request `split-debuginfo`"

### ISSUE THREAD

**Issue by matthiasbeyer** [kbknapp/cargo-outdated#355]
cargo-outdated fails calling rustc with

```
unknown print request `split-debuginfo`
```

See here for example:

https://github.com/TheNeikos/type_description/actions/runs/5308811255/jobs/9608812705?pr=217

I assume this happens because 0.12.0 changed something that wasn't in 0.11.x? The CI job from above uses `rustc 1.65.0`, which should be MSRV of cargo-outdated according to the changelog.

**Comment by kbknapp** [comment]
I haven't investigated yet, but I'm assuming this is caused by upgrading `cargo` to v0.70 which we did in order to take advantage of the sparse registry protocol.

My guess is that the MSRV to compile 1.65 as noted, but the MSRV to *run* is something higher. And as CI only checks the MSRV to compile I could see how this could slip in. Although I'm not exactly sure how to communicate that. I'll put some thought into it and do some testing.
